server:
  port: 8088
spring:
  application:
    #应用的名称，可选
    name: reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: qwer1234
  servlet:
    multipart:
      max-file-size: 5MB # 默认1MB
      enabled: true
      max-request-size: 200MB
  redis:
    host: 192.168.52.128
    port: 6379
    password: qwer1234
    database: 1
  cache:
    redis:
      time-to-live: 1800000 #缓存数据过期时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
files:
  upload:
    path: D:/JAVA/IDEA/IDEAProjects/reggie/files/
#    path: /home/files/
